/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_;


import com.accenture.flowershop.be.entity.jooqent.public_.tables.Admin;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Customer;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Flower;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.FlywaySchemaHistory;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.OrderInfo;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Orders;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.AdminRecord;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.CustomerRecord;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.FlowerRecord;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.FlywaySchemaHistoryRecord;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.OrderInfoRecord;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.OrdersRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;
    public static final UniqueKey<FlowerRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;
    public static final UniqueKey<OrdersRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<OrderInfoRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AdminRecord> CONSTRAINT_3 = Internal.createUniqueKey(Admin.ADMIN, "CONSTRAINT_3", Admin.ADMIN.LOGIN);
        public static final UniqueKey<CustomerRecord> CONSTRAINT_5 = Internal.createUniqueKey(Customer.CUSTOMER, "CONSTRAINT_5", Customer.CUSTOMER.LOGIN);
        public static final UniqueKey<FlowerRecord> CONSTRAINT_7 = Internal.createUniqueKey(Flower.FLOWER, "CONSTRAINT_7", Flower.FLOWER.NAME);
        public static final UniqueKey<OrdersRecord> CONSTRAINT_8 = Internal.createUniqueKey(Orders.ORDERS, "CONSTRAINT_8", Orders.ORDERS.ORDERID);
        public static final UniqueKey<OrderInfoRecord> CONSTRAINT_4 = Internal.createUniqueKey(OrderInfo.ORDER_INFO, "CONSTRAINT_4", OrderInfo.ORDER_INFO.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
    }
}
