/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_;


import com.accenture.flowershop.be.entity.jooqent.DefaultCatalog;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Admin;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Customer;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Flower;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.FlywaySchemaHistory;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.OrderInfo;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Orders;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -415607046;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ADMIN</code>.
     */
    public final Admin ADMIN = com.accenture.flowershop.be.entity.jooqent.public_.tables.Admin.ADMIN;

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = com.accenture.flowershop.be.entity.jooqent.public_.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.FLOWER</code>.
     */
    public final Flower FLOWER = com.accenture.flowershop.be.entity.jooqent.public_.tables.Flower.FLOWER;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public final Orders ORDERS = com.accenture.flowershop.be.entity.jooqent.public_.tables.Orders.ORDERS;

    /**
     * The table <code>PUBLIC.ORDER_INFO</code>.
     */
    public final OrderInfo ORDER_INFO = com.accenture.flowershop.be.entity.jooqent.public_.tables.OrderInfo.ORDER_INFO;

    /**
     * The table <code>PUBLIC.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.accenture.flowershop.be.entity.jooqent.public_.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ORDER_INFO_SEQ,
            Sequences.ORDER_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Admin.ADMIN,
            Customer.CUSTOMER,
            Flower.FLOWER,
            Orders.ORDERS,
            OrderInfo.ORDER_INFO,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }
}
