/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.ORDER_INFO_SEQ</code>
     */
    public static final Sequence<Long> ORDER_INFO_SEQ = new SequenceImpl<Long>("ORDER_INFO_SEQ", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.ORDER_SEQ</code>
     */
    public static final Sequence<Long> ORDER_SEQ = new SequenceImpl<Long>("ORDER_SEQ", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
