/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_;


import com.accenture.flowershop.be.entity.jooqent.public_.tables.Admin;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Customer;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Flower;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.FlywaySchemaHistory;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.OrderInfo;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.Orders;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ADMIN</code>.
     */
    public static final Admin ADMIN = com.accenture.flowershop.be.entity.jooqent.public_.tables.Admin.ADMIN;

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = com.accenture.flowershop.be.entity.jooqent.public_.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.FLOWER</code>.
     */
    public static final Flower FLOWER = com.accenture.flowershop.be.entity.jooqent.public_.tables.Flower.FLOWER;

    /**
     * The table <code>PUBLIC.ORDERS</code>.
     */
    public static final Orders ORDERS = com.accenture.flowershop.be.entity.jooqent.public_.tables.Orders.ORDERS;

    /**
     * The table <code>PUBLIC.ORDER_INFO</code>.
     */
    public static final OrderInfo ORDER_INFO = com.accenture.flowershop.be.entity.jooqent.public_.tables.OrderInfo.ORDER_INFO;

    /**
     * The table <code>PUBLIC.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.accenture.flowershop.be.entity.jooqent.public_.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
