
package com.accenture.flowershop.fe.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "increaseFlowersStockSize", targetNamespace = "http://SOAP.fe.flowershop.accenture.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IncreaseFlowersStockSize {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "increaseFlowersStockSize", targetNamespace = "http://SOAP.fe.flowershop.accenture.com/", className = "com.accenture.flowershop.fe.soap.IncreaseFlowersStockSize_Type")
    @ResponseWrapper(localName = "increaseFlowersStockSizeResponse", targetNamespace = "http://SOAP.fe.flowershop.accenture.com/", className = "com.accenture.flowershop.fe.soap.IncreaseFlowersStockSizeResponse")
    public boolean increaseFlowersStockSize(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
