/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_.tables;


import com.accenture.flowershop.be.entity.jooqent.public_.Indexes;
import com.accenture.flowershop.be.entity.jooqent.public_.Keys;
import com.accenture.flowershop.be.entity.jooqent.public_.Public;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.FlowerRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Flower extends TableImpl<FlowerRecord> {

    private static final long serialVersionUID = -1351334622;

    /**
     * The reference instance of <code>PUBLIC.FLOWER</code>
     */
    public static final Flower FLOWER = new Flower();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FlowerRecord> getRecordType() {
        return FlowerRecord.class;
    }

    /**
     * The column <code>PUBLIC.FLOWER.NAME</code>.
     */
    public final TableField<FlowerRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.FLOWER.COST</code>.
     */
    public final TableField<FlowerRecord, BigDecimal> COST = createField("COST", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>PUBLIC.FLOWER.STOCK</code>.
     */
    public final TableField<FlowerRecord, Integer> STOCK = createField("STOCK", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>PUBLIC.FLOWER</code> table reference
     */
    public Flower() {
        this(DSL.name("FLOWER"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.FLOWER</code> table reference
     */
    public Flower(String alias) {
        this(DSL.name(alias), FLOWER);
    }

    /**
     * Create an aliased <code>PUBLIC.FLOWER</code> table reference
     */
    public Flower(Name alias) {
        this(alias, FLOWER);
    }

    private Flower(Name alias, Table<FlowerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Flower(Name alias, Table<FlowerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Flower(Table<O> child, ForeignKey<O, FlowerRecord> key) {
        super(child, key, FLOWER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FlowerRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FlowerRecord>> getKeys() {
        return Arrays.<UniqueKey<FlowerRecord>>asList(Keys.CONSTRAINT_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Flower as(String alias) {
        return new Flower(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Flower as(Name alias) {
        return new Flower(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Flower rename(String name) {
        return new Flower(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Flower rename(Name name) {
        return new Flower(name, null);
    }
}
