/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_.tables;


import com.accenture.flowershop.be.entity.jooqent.public_.Indexes;
import com.accenture.flowershop.be.entity.jooqent.public_.Keys;
import com.accenture.flowershop.be.entity.jooqent.public_.Public;
import com.accenture.flowershop.be.entity.jooqent.public_.tables.records.OrderInfoRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderInfo extends TableImpl<OrderInfoRecord> {

    private static final long serialVersionUID = -2025663291;

    /**
     * The reference instance of <code>PUBLIC.ORDER_INFO</code>
     */
    public static final OrderInfo ORDER_INFO = new OrderInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderInfoRecord> getRecordType() {
        return OrderInfoRecord.class;
    }

    /**
     * The column <code>PUBLIC.ORDER_INFO.ID</code>.
     */
    public final TableField<OrderInfoRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORDER_INFO.ORDERID</code>.
     */
    public final TableField<OrderInfoRecord, Integer> ORDERID = createField("ORDERID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ORDER_INFO.FLOWER</code>.
     */
    public final TableField<OrderInfoRecord, String> FLOWER = createField("FLOWER", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.ORDER_INFO.FLOWERAMOUNT</code>.
     */
    public final TableField<OrderInfoRecord, Integer> FLOWERAMOUNT = createField("FLOWERAMOUNT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ORDER_INFO.COST</code>.
     */
    public final TableField<OrderInfoRecord, BigDecimal> COST = createField("COST", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * The column <code>PUBLIC.ORDER_INFO.ITEM_COST</code>.
     */
    public final TableField<OrderInfoRecord, BigDecimal> ITEM_COST = createField("ITEM_COST", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * Create a <code>PUBLIC.ORDER_INFO</code> table reference
     */
    public OrderInfo() {
        this(DSL.name("ORDER_INFO"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.ORDER_INFO</code> table reference
     */
    public OrderInfo(String alias) {
        this(DSL.name(alias), ORDER_INFO);
    }

    /**
     * Create an aliased <code>PUBLIC.ORDER_INFO</code> table reference
     */
    public OrderInfo(Name alias) {
        this(alias, ORDER_INFO);
    }

    private OrderInfo(Name alias, Table<OrderInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderInfo(Name alias, Table<OrderInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OrderInfo(Table<O> child, ForeignKey<O, OrderInfoRecord> key) {
        super(child, key, ORDER_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderInfoRecord>>asList(Keys.CONSTRAINT_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfo as(String alias) {
        return new OrderInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfo as(Name alias) {
        return new OrderInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderInfo rename(String name) {
        return new OrderInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderInfo rename(Name name) {
        return new OrderInfo(name, null);
    }
}
