/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_.tables.records;


import com.accenture.flowershop.be.entity.jooqent.public_.tables.Orders;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record6<Integer, String, BigDecimal, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 600698138;

    /**
     * Setter for <code>PUBLIC.ORDERS.ORDERID</code>.
     */
    public void setOrderid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.ORDERID</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.LOGIN</code>.
     */
    public void setLogin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.LOGIN</code>.
     */
    public String getLogin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.TOTAL</code>.
     */
    public void setTotal(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.TOTAL</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.OPENDATE</code>.
     */
    public void setOpendate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.OPENDATE</code>.
     */
    public Timestamp getOpendate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.CLOSEDATE</code>.
     */
    public void setClosedate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.CLOSEDATE</code>.
     */
    public Timestamp getClosedate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ORDERS.STATE</code>.
     */
    public void setState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDERS.STATE</code>.
     */
    public String getState() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, BigDecimal, Timestamp, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, BigDecimal, Timestamp, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Orders.ORDERS.ORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Orders.ORDERS.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Orders.ORDERS.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Orders.ORDERS.OPENDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Orders.ORDERS.CLOSEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Orders.ORDERS.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getOpendate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getClosedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getOpendate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getClosedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value1(Integer value) {
        setOrderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value2(String value) {
        setLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value3(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value4(Timestamp value) {
        setOpendate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value5(Timestamp value) {
        setClosedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value6(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord values(Integer value1, String value2, BigDecimal value3, Timestamp value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer orderid, String login, BigDecimal total, Timestamp opendate, Timestamp closedate, String state) {
        super(Orders.ORDERS);

        set(0, orderid);
        set(1, login);
        set(2, total);
        set(3, opendate);
        set(4, closedate);
        set(5, state);
    }
}
