/*
 * This file is generated by jOOQ.
 */
package com.accenture.flowershop.be.entity.jooqent.public_.tables.records;


import com.accenture.flowershop.be.entity.jooqent.public_.tables.OrderInfo;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderInfoRecord extends UpdatableRecordImpl<OrderInfoRecord> implements Record6<Integer, Integer, String, Integer, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1620872129;

    /**
     * Setter for <code>PUBLIC.ORDER_INFO.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_INFO.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_INFO.ORDERID</code>.
     */
    public void setOrderid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_INFO.ORDERID</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_INFO.FLOWER</code>.
     */
    public void setFlower(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_INFO.FLOWER</code>.
     */
    public String getFlower() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_INFO.FLOWERAMOUNT</code>.
     */
    public void setFloweramount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_INFO.FLOWERAMOUNT</code>.
     */
    public Integer getFloweramount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_INFO.COST</code>.
     */
    public void setCost(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_INFO.COST</code>.
     */
    public BigDecimal getCost() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ORDER_INFO.ITEM_COST</code>.
     */
    public void setItemCost(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ORDER_INFO.ITEM_COST</code>.
     */
    public BigDecimal getItemCost() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Integer, BigDecimal, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Integer, BigDecimal, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrderInfo.ORDER_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrderInfo.ORDER_INFO.ORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OrderInfo.ORDER_INFO.FLOWER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OrderInfo.ORDER_INFO.FLOWERAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return OrderInfo.ORDER_INFO.COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return OrderInfo.ORDER_INFO.ITEM_COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFlower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getFloweramount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getItemCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFlower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFloweramount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getItemCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord value2(Integer value) {
        setOrderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord value3(String value) {
        setFlower(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord value4(Integer value) {
        setFloweramount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord value5(BigDecimal value) {
        setCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord value6(BigDecimal value) {
        setItemCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderInfoRecord values(Integer value1, Integer value2, String value3, Integer value4, BigDecimal value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderInfoRecord
     */
    public OrderInfoRecord() {
        super(OrderInfo.ORDER_INFO);
    }

    /**
     * Create a detached, initialised OrderInfoRecord
     */
    public OrderInfoRecord(Integer id, Integer orderid, String flower, Integer floweramount, BigDecimal cost, BigDecimal itemCost) {
        super(OrderInfo.ORDER_INFO);

        set(0, id);
        set(1, orderid);
        set(2, flower);
        set(3, floweramount);
        set(4, cost);
        set(5, itemCost);
    }
}
